// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MudBlazorPWA.Shared.Data;

#nullable disable

namespace MudBlazorPWA.Shared.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230221215916_SqLite_Initial")]
    partial class SqLiteInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("MudBlazorPWA.Shared.Models.CodeType", b =>
                {
                    b.Property<int>("CodeTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("CodeType");

                    b.HasKey("CodeTypeId");

                    b.ToTable("CodeType");

                    b.HasData(
                        new
                        {
                            CodeTypeId = 0,
                            Name = "Stop"
                        },
                        new
                        {
                            CodeTypeId = 1,
                            Name = "Almost"
                        },
                        new
                        {
                            CodeTypeId = 2,
                            Name = "Data"
                        },
                        new
                        {
                            CodeTypeId = 3,
                            Name = "Layer"
                        },
                        new
                        {
                            CodeTypeId = 4,
                            Name = "Material"
                        },
                        new
                        {
                            CodeTypeId = 5,
                            Name = "None"
                        });
                });

            modelBuilder.Entity("MudBlazorPWA.Shared.Models.WindingCode", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("CodeTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FolderPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.HasIndex("CodeTypeId");

                    b.ToTable("WindingCodes");
                });

            modelBuilder.Entity("MudBlazorPWA.Shared.Models.WindingCode", b =>
                {
                    b.HasOne("MudBlazorPWA.Shared.Models.CodeType", "CodeType")
                        .WithMany()
                        .HasForeignKey("CodeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MudBlazorPWA.Shared.Models.Media", "Media", b1 =>
                        {
                            b1.Property<string>("WindingCodeCode")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Pdf")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ReferenceFolder")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Video")
                                .HasColumnType("TEXT");

                            b1.HasKey("WindingCodeCode");

                            b1.ToTable("WindingCodes");

                            b1.WithOwner()
                                .HasForeignKey("WindingCodeCode");
                        });

                    b.Navigation("CodeType");

                    b.Navigation("Media")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
