// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MudBlazorPWA.Shared.Data;

#nullable disable

namespace MudBlazorPWA.Shared.Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("MudBlazorPWA.Shared.Models.CodeType", b =>
                {
                    b.Property<int>("CodeTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("CodeType");

                    b.HasKey("CodeTypeId");

                    b.ToTable("CodeType");

                    b.HasData(
                        new
                        {
                            CodeTypeId = 0,
                            Name = "Stop"
                        },
                        new
                        {
                            CodeTypeId = 1,
                            Name = "Almost"
                        },
                        new
                        {
                            CodeTypeId = 2,
                            Name = "Data"
                        },
                        new
                        {
                            CodeTypeId = 3,
                            Name = "Layer"
                        },
                        new
                        {
                            CodeTypeId = 4,
                            Name = "Material"
                        },
                        new
                        {
                            CodeTypeId = 5,
                            Name = "None"
                        });
                });

            modelBuilder.Entity("MudBlazorPWA.Shared.Models.WindingCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("CodeTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Division")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FolderPath")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("Stop");

                    b.HasKey("Id");

                    b.HasIndex("CodeTypeId");

                    b.HasIndex("Code", "Division")
                        .IsUnique();

                    b.ToTable("WindingCodes");
                });

            modelBuilder.Entity("MudBlazorPWA.Shared.Models.WindingCode", b =>
                {
                    b.HasOne("MudBlazorPWA.Shared.Models.CodeType", "CodeType")
                        .WithMany()
                        .HasForeignKey("CodeTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("MudBlazorPWA.Shared.Models.Media", "Media", b1 =>
                        {
                            b1.Property<int>("WindingCodeId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Pdf")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT")
                                .HasColumnName("Pdf");

                            b1.Property<string>("RefMedia")
                                .HasColumnType("TEXT")
                                .HasColumnName("RefMedia");

                            b1.Property<string>("Video")
                                .HasMaxLength(255)
                                .HasColumnType("TEXT")
                                .HasColumnName("Video");

                            b1.HasKey("WindingCodeId");

                            b1.ToTable("WindingCodes");

                            b1.WithOwner()
                                .HasForeignKey("WindingCodeId");
                        });

                    b.Navigation("CodeType");

                    b.Navigation("Media")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
